fix(windows): Fix windows shell
Signed-off-by: dark0dave <dark0dave@mykolab.com>

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -3,7 +3,7 @@ on:
   pull_request:
 concurrency:
   group: ${{ github.ref }}-${{ github.workflow }}
-  cancel-in-progress: true
+  # cancel-in-progress: true
 jobs:
   build:
     name: build
@@ -35,16 +35,53 @@ jobs:
   windows-build:
     name: windows build
     runs-on: windows-latest
+    defaults:
+      run:
+        shell: bash
     steps:
       - name: Checkout the code
         uses: actions/checkout@v4
-      - name: Set up Cygwin
-        uses: egor-tensin/setup-cygwin@v4
+      - name: Set up cache
+        uses: actions/cache@v4
         with:
-          packages: binutils make cmake mingw-gcc-core gcc gcc-g++ bison flex
-      - name: build elkhound
+          path: ~/.buildcache
+          key: ${{ runner.os }}-win-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-win-
+      - name: install MSVC 2017
+        shell: pwsh
         run: |
+          $vs_url = "https://aka.ms/vs/15/release/vs_BuildTools.exe"
+          Invoke-WebRequest -Uri $vs_url -OutFile "vs_buildtools.exe"
+          if (-not (Test-Path "vs_buildtools.exe")) {
+              Write-Error "Failed to download VS Build Tools"
+              exit 1
+          }
+          $components = @(
+            "Microsoft.VisualStudio.Workload.VCTools",
+            "Microsoft.VisualStudio.Component.Windows10SDK.19041",
+            "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
+            "Microsoft.VisualStudio.Component.VC.CMake.Project"
+          )
+          $componentArgs = ($components | ForEach-Object { "--add $_" }) -join " "
+          $installCmd = ".\vs_buildtools.exe --quiet --norestart --force --wait --installPath C:\BuildTools $componentArgs"
+          Start-Process -FilePath ".\vs_buildtools.exe" -ArgumentList $installCmd.Split() -Wait -PassThru
+      - name: install deps
+        run: |
+          choco install --stoponfirstfailure -y winflexbison3
+      - name: Check components
+        shell: cmd
+        run: |
+          call "C:\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
+          cmake -version
+          msbuild -version
           mkdir build
-          cmake -Wno-dev -S src -B build -DEXTRAS=OFF -DOCAML=OFF -DCMAKE_BUILD_TYPE=Release
-          make -C build
-          ls D:\a\elkhound\elkhound\build\elkhound
+          cmake -Wno-dev -B build -G Ninja -S src -DFLEX_INCLUDE_DIR=C:\ProgramData\chocolatey\lib\winflexbison3\tools -DCMAKE_BUILD_TYPE=Release
+          cd build
+          ninja
+        env:
+          CMAKE_LEGACY_CYGWIN_WIN32: 0
+      - uses: actions/upload-artifact@v4
+        with:
+          name: windows-elkhound
+          path: elkhound.exe
